# Recipe for metapackages to install CPU and CUDA versions of LightGBM

{% set version = "3.1.1" %}

package:
  name: py-lightgbm{{ '-cpu' if build_type == 'cpu' else '' }}
  version: {{ version }}

build:
  number: 4
  string: py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}   #[build_type == 'cpu']
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']

requirements:
  run:
    - liblightgbm-base {{ version }}*
    - py-lightgbm-base {{ version }}*
    - _lightgbm_select =={{ lightgbm_select_version }}*
    - python {{ python }}
    - cudatoolkit {{ cudatoolkit }} #[build_type == 'cuda']

about:
  home: https://github.com/microsoft/LightGBM
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: A metapackage for selecting a LightGBM variant.
  description: A metapackage for selecting a LightGBM variant.
  doc_url: https://github.com/microsoft/LightGBM/tree/v{{ version }}/docs
  dev_url: https://github.com/microsoft/LightGBM/tree/v{{ version }}

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

