name: Open-CE Feedstock Merge Triggers

on:
  pull_request:
    branches: [main]

jobs:
  version_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: "3.8"
      - uses: bethune-bryant/open-ce/.github/actions/feedstock-merge@fix_merge_workflow
